<a href="https://colab.research.google.com/github/iestleija/4808-Programacion/blob/Unidad2/Unidad2/Practices/Practica19_266229.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

,**Maestría en Inteligencia Artificial y Analítica de Datos**

- Curso: Programación para Analítica Descriptiva y Predictiva

- Semestre: Enero-Junio

- Profesor: Dr. Vicente García Jiménez
- Práctica:
Práctica #19: Datos Duplicados
- Alumno: Ismael Estrada Leija
- Matrícula: 266229


#Práctica #19: Datos Duplicados

El objetivo de esta actividad es que los estudiantes pongan en práctica lo visto en el vídeo y en el notebook que se proporciona
## Instrucciones:
1. Descarga el archivo dirtydata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv  en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

Sube un archivo txt que contenga la liga a tu notebook

## Preparación del entorno

In [188]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [189]:
# Importación de bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def print_bold(msg):
    print("\n\033[1m" + msg + "\033[0m")
file_path = '/content/drive/MyDrive/4808-programacion/U02/P19/dirtydata.csv';

## Ejercicio 01 Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration

### 1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.

In [190]:
dirty_df = pd.read_csv(file_path)
print_bold("Carga de dataframe original para ejercicio 1")
dirty_df.head()

Carga de dataframe original para ejercicio 1

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

### 2. Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime
3. Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.

In [191]:
# calculating exercise 1 duplicates in a dedicated copy
dirty_df_dup1 = dirty_df.copy()
print_bold("Datos duplicados en la columna Duration")

# Add a flag to mark the duplicate rows.
dirty_df_dup1["Duration Duplicate"] = dirty_df.duplicated(subset=["Duration"],keep=False)

# Show the counting
dirty_df_dup1["Duration Duplicate"].value_counts()

Datos duplicados en la columna Duration

Duration Duplicate
True     30
False     2
Name: count, dtype: int64

### 4. Filtra los datos y obten los registros sin duplicados

In [192]:
print_bold("Filas sin duplicados en columna Duration")
dirty_df_dup1[dirty_df_dup1["Duration Duplicate"] == False]

Filas sin duplicados en columna Duration

   Duration          Date  Pulse  Maxpulse  Calories  Duration Duplicate
7       450  '2020/12/08'    104       134     253.3               False
8        30  '2020/12/09'    109       133     195.1               False

## Ejercicio 02 Duplicidad Parcial Dos columnas: Contar y Filtrar los registros duplicados en Pulse y MaxPulse

### 1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.

In [193]:
dirty_df = pd.read_csv(file_path)
print_bold("Carga de dataframe original para ejercicio  2")
dirty_df.head()

Carga de dataframe original para ejercicio  2

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

### 2. Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse
3. Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
---
En esta primera instancia se marcan los duplicados sin recuperación con `keep=False`

In [210]:
# calculating exercise 2 duplicates in a dedicated copy
dirty_df_dup2 = dirty_df.copy()
print_bold("Datos duplicados usando las columnas Pulse y Maxpulse, con keep=False")
dirty_df_dup2["Pulse and Maxpulse Duplicate"] = dirty_df_dup2.duplicated(subset=["Pulse", "Maxpulse"],keep=False)
dirty_df_dup2["Pulse and Maxpulse Duplicate"].value_counts()

Datos duplicados usando las columnas Pulse y Maxpulse con keep=False

Pulse and Maxpulse Duplicate
False    28
True      4
Name: count, dtype: int64

In [205]:
print_bold("Filas duplicados usando las columnas Pulse y Maxpulse, con keep=False")
dirty_df_dup2[dirty_df_dup2["Pulse and Maxpulse Duplicate"] == True]

Filas duplicados usando las columnas Pulse y Maxpulse

,Duration,Date,Pulse,Maxpulse,Calories,Pulse and Maxpulse Duplicate
11,60,'2020/12/12',100,120,250.7,True
12,60,'2020/12/12',100,120,250.7,True
17,60,'2020/12/17',100,120,300.0,True

### 4. Filtra los datos y obten los registros cuando keep = 'last'
---
Nótese la diferencia: cuando `keep='last'`, se recupera uno de los duplicados, en este caso la última aparición.

In [212]:
dirty_df_dup2["Pulse and Maxpulse Duplicate"] = dirty_df_dup2.duplicated(subset=["Pulse", "Maxpulse"],keep='last')
print_bold("Filas duplicados usando las columnas Pulse y Maxpulse con keep='last'")
dirty_df_dup2[dirty_df_dup2["Pulse and Maxpulse Duplicate"] == True]

Filas duplicados usando las columnas Pulse y Maxpulse con keep='last'

,Duration,Date,Pulse,Maxpulse,Calories,Pulse and Maxpulse Duplicate
11,60,'2020/12/12',100,120,250.7,True
12,60,'2020/12/12',100,120,250.7,True
17,60,'2020/12/17',100,120,300.0,True

## Ejercicio 03 Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados

1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.

In [197]:
dirty_df = pd.read_csv(file_path)
print_bold("Carga de dataframe original para ejercicio  3")
dirty_df.head()

Carga de dataframe original para ejercicio  3

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

2. Cuenta la cantidad de registros duplicados exactos (todas las columnas)

In [208]:
# calculating exercise 3 duplicates in a dedicated copy
dirty_df_dup3 = dirty_df.copy()
dirty_df_dup3["Duplicate"] = dirty_df_dup3.duplicated(keep=False)
print_bold("Conteo de filas completas duplicadas en el dataframe original")
dirty_df_dup3["Duplicate"].value_counts()

Conteo de filas completas duplicadas en el dataframe original

Duplicate
False    30
True      2
Name: count, dtype: int64

### 3. Utiliza sum() e imprime la cantidad de registros con duplicidad exacta

In [199]:
total_duplicates = dirty_df_dup3.duplicated(keep=False).sum()
print_bold(f"En total hay {total_duplicates} filas completas duplicadas.")

Hay 2 filas duplicadas.

### 4. Filtra los datos y obten los registros cuando keep = 'last'

In [200]:
dirty_row_duplicates= dirty_df_dup3[dirty_df_dup3.duplicated(keep='last')]
print_bold("Filas duplicadas dejando una (la última) de cada conjunto de filas duplicadas")
print(dirty_row_duplicates)

Filas duplicadas dejando una (la última) de cada conjunto de filas duplicadas
    Duration          Date  Pulse  Maxpulse  Calories  Duplicate
11        60  '2020/12/12'    100       120     250.7       True

## Ejercicio 04: Cálculo de la media con duplicados y sin duplicados

### 1. Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.

In [201]:
dirty_df = pd.read_csv(file_path)
print_bold("Carga de dataframe original para ejercicio 4")
dirty_df.head()

Carga de dataframe original para ejercicio 4

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

### 2. Calcula e imprime la media de las columnas Pulse y MaxPulse

In [202]:
print_bold("Media aritmética de las columnas Pulse y Maxpulse con datos originales")
print(dirty_df[["Pulse", "Maxpulse"]].mean())
print_bold("Forma inicial de dataframe original")
dirty_df.shape

Media aritmética de las columnas Pulse y Maxpulse con datos originales
Pulse       103.5
Maxpulse    128.5
dtype: float64

Forma inicial de dataframe original

(32, 5)

### 3. Identifica los valores duplicados en las columnas Pulse y MaxPulse (Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias

In [213]:
dirty_df_dup4 = dirty_df.drop_duplicates(subset=["Pulse", "Maxpulse"], keep="last")
print_bold("Forma del dataframe sin duplicados para columnas Pulse y Maxpulse")
print_bold("Se eliminaron 3 filas")
dirty_df_dup4.shape

Forma del dataframe sin duplicados para columnas Pulse y Maxpulse

Se eliminaron 3 filas

(29, 5)

### 4. Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse

In [209]:
print_bold("Valores del dataframe ORIGINAL en columnas Pulse y Maxpulse")
print(dirty_df[["Pulse", "Maxpulse"]].mean())
print_bold("Valores del dataframe SIN DUPLICADOS en columnas Pulse y Maxpulse")
print(dirty_df_dup4[["Pulse", "Maxpulse"]].mean())

Valores del dataframe ORIGINAL en columnas Pulse y Maxpulse
Pulse       103.5
Maxpulse    128.5
dtype: float64

Valores del dataframe SIN DUPLICADOSs en columnas Pulse y Maxpulse
Pulse       103.862069
Maxpulse    129.379310
dtype: float64

# Conclusión
Usando como referencia principal el video proporcionado por el docente García Jímenez, V. (2025). Datos Duplicados [Video de Youtube].
 y la documentación de pandas, (Pandas team, 2026) se completaron los ejercicios de la presente práctica.

#Referencias
García Jímenez, V. (2025). Datos Duplicados [Video de Youtube].

Pandas team. (2026). pandas documentation—Pandas 3.0.0 documentation. https://pandas.pydata.org/docs/index.html